//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telepomocnik_DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    using TelePomocnikWeb;
    
    public partial class TelePomocnikDbEntities1 : DbContext
    {
        public TelePomocnikDbEntities1()
            : base("name=TelePomocnikDbEntities1")
        {
        }
    
        public DbSet<Company> Company { get; set; }
        public DbSet<Contact> Contact { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<Telemarketer> Telemarketer { get; set; }
        public DbSet<Event> Event { get; set; }
        public DbSet<MustCallInformation> MustCallInformation { get; set; }
        public DbSet<ContactHistory> ContactHistory { get; set; }
    
        
    }
}
